<?php

/**
 * @file
 * Bootstrap sub-theme.
 *
 * Place your custom PHP code in this file.
 */

/**
 * Implements hook_preprocess_HOOK().
 */
//function exam_preprocess_field(&$variables) {
//  if($variables['element']['#field_name'] == 'field_date' && $variables['element']['#items']['definition']['fieldStorage']['id'] == 'node.field_date') {
//    var_dump($variables['element']['#items']);
//    echo ("temp test");
//  }
//}

//field_name' => string 'field_date

